name: nested_choice_list
description: "A flutter package for handling nested list item selection without limitation for the depth of the nested list."
version: 1.1.1
homepage: https://github.com/TalebRafiepour/nested_choice_list
repository: https://github.com/TalebRafiepour/nested_choice_list
issue_tracker: https://github.com/TalebRafiepour/nested_choice_list/issues

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
